### ISSUE TITLE
Results empty

### ISSUE THREAD

**Issue by teavanist** [alviser/mitch#1]
Hi, 
I ran this tool on one of the websites and I found that it does not show any results. Basically after the following line 

_the following URLs may be vulnerable to CSRFs (check console output for more details):_

the result page is empty and there is nothing on the console 
Does this mean the tool did not find any URL to be vulnerable?

**Comment by alviser** [comment]
Hi teavanist,
 you should have a bunch of output in the console telling you about the checks being made and then, indeed, if the results are empty that's an indication that mitch didn't find anything.
Please keep in mind that there might be false negatives, though!
(these might happen, mostly, in the form of URLs mitch didn't deemed as sensitive thus not checking them)

Thank you for using it!
